version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust based on your frontend app's port
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust based on your backend app's port
    volumes:
      - ./server:/app
      - db_data:/data  # For database persistence

volumes:
  db_data: